### ISSUE TITLE
Error: 5 NOT_Found: Requested Entity was not found.

### ISSUE THREAD

**Issue by jasonisamilehigh** [sararob/automl-api-demo#2]
When I upload a file via my Firebase storage bucket I can see that the function is triggered.  However I am continuously getting the following error when I look at the Function's Log:

callCustomModel
 error occurred { Error: 5 NOT_FOUND: Requested entity was not found.
    at Object.exports.createStatusError (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 5,
  metadata: Metadata { _internal_repr: { 'grpc-server-stats-bin': [Object] } },
  details: 'Requested entity was not found.' }
  
  callCustomModel
  AutoML API Error:  { Error: 5 NOT_FOUND: Requested entity was not found.
    at Object.exports.createStatusError (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/user_code/node_modules/@google-cloud/automl/node_modules/grpc/src/client_interceptors.js:

**Comment by jasonisamilehigh** [comment]
For anyone else who runs into this issue, I was able to resolve by correcting the const automl_model value in the index.js file.  I'm not sure if it's standard but my automl_model was the ID under the Model  page.  It wasn't the name or the Dataset ID.
